# Generated by Django 5.0 on 2024-07-23 10:05

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTimeUpdation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ItemNo', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Blocked', models.BooleanField(blank=True, default=False, null=True)),
                ('SearchDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('BaseUnitOfMeasure', models.CharField(blank=True, max_length=50, null=True)),
                ('ParentCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('ItemCategoryCode', models.CharField(blank=True, max_length=50, null=True)),
                ('ItemSubCategoryCode', models.CharField(blank=True, max_length=50, null=True)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('NetWeight', models.FloatField(blank=True, null=True)),
                ('Packaging', models.CharField(blank=True, max_length=50, null=True)),
                ('BarCode', models.CharField(blank=True, max_length=20, null=True)),
                ('SalesUnitOfMeasure', models.CharField(blank=True, max_length=50, null=True)),
                ('WeightDescription', models.CharField(blank=True, max_length=10, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('BrandLink', models.CharField(blank=True, max_length=255, null=True)),
                ('GTIN', models.CharField(blank=True, max_length=20, null=True)),
                ('PurchasingCode', models.CharField(blank=True, max_length=50, null=True)),
                ('LastDateTimeModified', models.DateTimeField(default=datetime.datetime(2024, 7, 23, 15, 5, 29, 913744))),
                ('SalesBlocked', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Srno', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('salestype', models.CharField(blank=True, max_length=100, null=True)),
                ('Salecode', models.CharField(blank=True, max_length=10, null=True)),
                ('ItemNo', models.CharField(blank=True, max_length=50, null=True)),
                ('UnitPrice', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('MinimumQuantity', models.IntegerField(blank=True, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('SystemModifiedAt', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount_including_vat', models.FloatField(blank=True, null=True)),
                ('total_amount_excluding_vat', models.FloatField(blank=True, null=True)),
                ('vat_amount', models.FloatField(blank=True, null=True)),
                ('date_time_created', models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 23, 15, 5, 29, 914746), null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('vat_rate', models.FloatField(blank=True, null=True)),
                ('total_amount_including_vat', models.FloatField(blank=True, null=True)),
                ('total_amount_excluding_vat', models.FloatField(blank=True, null=True)),
                ('vat_amount', models.FloatField(blank=True, null=True)),
                ('date_time_created', models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 23, 15, 5, 29, 915744), null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='items.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
