# Generated by Django 5.0.2 on 2024-07-24 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_cart_date_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 24, 17, 33, 22, 330079), null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 24, 17, 33, 22, 330079), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='LastDateTimeModified',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 17, 33, 22, 329079)),
        ),
    ]
