# Generated by Django 5.0 on 2024-09-20 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_cart_date_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 20, 10, 0, 14, 601735), null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 20, 10, 0, 14, 602733), null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_amount_excluding_vat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_amount_including_vat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='vat_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='vat_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='LastDateTimeModified',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 10, 0, 14, 600736)),
        ),
    ]
