# Generated by Django 5.0 on 2024-09-20 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_cart_date_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 20, 10, 0, 52, 829458), null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 20, 10, 0, 52, 830455), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='LastDateTimeModified',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 10, 0, 52, 828454)),
        ),
    ]
